name: RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip

    - name: Enable RDP
     run: |
      net user runneradmin Password123
       net localgroup administrators runneradmin /add || exit 0

    - name: Start Ngrok
      run: |
        .\ngrok.exe tcp 3389
